### ISSUE TITLE
Unplug usb camera while it is still in use and application end up with ANR.

### ISSUE THREAD

**Issue by chenxi1991** [saki4510t/UVCCamera#472]
Input dispatching timed out

ANR Input dispatching timed out (Waiting because the touched window's input channel is full. Outbound queue length: 1. Wait queue length: 32.)

1 java.lang.Object.wait!(Native method)

2 com.serenegiant.usbcameracommon.AbstractUVCCameraHandler.void stopPreview()(AbstractUVCCameraHandler.java:208)

3 com.serenegiant.usbcameracommon.AbstractUVCCameraHandler.void close()(AbstractUVCCameraHandler.java:175)

**Comment by xiedong2002** [comment]
Unluckily , The issue occurs on me . It can easily be reproduced on Android 7.1 with Rockchip 3288. I am trying to debug the issue. It might be caused by the fact that a  lock is not fired since some of outstanding transfer requests are not handled properly ( cancelled or completed). Continue ......

**Comment by mingtong** [comment]
You should handle the event when unplug camera and do release things.

**Comment by leifeng1991** [comment]
@chenxi1991 Solution to the do
