### ISSUE TITLE
[question] Take a picture

### ISSUE THREAD

**Issue by palmerabollo** [saki4510t/UVCCamera#48]
What is the best way to capture a single snapshot with the USB camera without processing all the video stream? Is there a function in the API to take a picture? Thank you for your help.

**Comment by saki4510t** [comment]
Hi,
Unfortunately there are no way to take picture only now. Only several cameras support still capture feature of UVC specification and I don't plan to support still capture feature of UVC specification on this repository now.
So if you want to capture a image without preview, you need to modify native library so that it can start streaming without preview(without `Surface`) and get a image then stop streaming.
Or you can pass `SurfaceTexture` as offscreen preview `Surface`, start streaming, take image and stop streaming.

Note: There is a possibility that first several video frames from camera are broken so it will be better to skip first several frames and then capture a image.

saki

**Comment by palmerabollo** [comment]
Thanks for the explanation and the tips, saki. I'll try with the offscreen preview, that seems easier than modifying the native library.

**Comment by saki4510t** [comment]
Hi,
Some hints for using SurfaceTexture as offscreen is available on `UVCCameraTextureView.java`, `RenderHandler.java` in `usbCameratest3` etc.
saki

**Comment by palmerabollo** [comment]
Ok. I'll take a look. I started with `usbCameratest4` because I also want to run it as a `Service` and take the picture when it receives an external notification (ex. an incoming SMS or when I press the volume buttons). That's why I don't need an `Activity` + a `Surface`. I hope that's possible...

**Comment by saki4510t** [comment]
`usbWebCameraTest4` also includes offscreen preview because offscreen is necessary for background service. But you need at least one `Activity` to keep permanent permission and install apt on your device (by limitation of Android OS itself).
saki

**Comment by palmerabollo** [comment]
Yes, that is not a problem. What I don't know is if it will continue working when the screen is off.

**Comment by ducanh841988** [comment]
Did you achieve taking picture @palmerabollo ?

**Comment by palmerabollo** [comment]
@ducanh841988 Yes. I can say that it's doable but it was just a quick & dirty experiment and I don't remember the details of how I managed to do it :(

**Comment by fengbenpaao** [comment]
if I use the onFremeCallback   to   get the frame date to  imgae  ?
 but  the data I get,  don't show  ok,    it will be green,  reb  。。。。

**Comment by akshayah3** [comment]
Did anyone achieve to do this?. Basically i want to capture the image in a background service without any preview or display

**Comment by KanwalKhan-20** [comment]
How to take picture of UVCCameraTextureView alongwith textview ?
I am only able to take screenshot of either UVCCameraTextureView or textview.

**Comment by Keerthana-N** [comment]
> @ducanh841988 Yes. I can say that it's doable but it was just a quick & dirty experiment and I don't remember the details of how I managed to do it :(

Hi Can you please share the solution.
